<?php
// $Id$
/**
 * @file
 * This module defines a new cck field and widget that provides an autocomplete field with a dropbox for storing multiple values.
 */

//test to see that the field is displayed otherwise the js is not needed and can create problems with other js
if(arg(0) == 'node') {
	drupal_add_js(drupal_get_path('module', 'autocomplete_dropbox').'/autoSuggest/jquery.autoSuggest.js', 'module');
	drupal_add_js(drupal_get_path('module', 'autocomplete_dropbox').'/autocomplete_dropbox.js', 'module'); // Can be moved to info file if so desired
	drupal_add_css(drupal_get_path('module', 'autocomplete_dropbox').'/autoSuggest/autoSuggest.css', 'module');
}
  
/**
 * Implementation of hook_menu
 * This module uses a custom autocomplete path because we need the term id in addition to the term name
 */
function autocomplete_dropbox_menu() {
  $items = array();
  $items['autocomplete_dropbox.json'] = array(
    'title' => 'Dropbox Autocomplete Widget',
    'page callback' => 'autocomplete_dropbox_autosuggest',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
  );
  return $items;
}

function autocomplete_dropbox_autosuggest() {
	$prefetch = TRUE;
  $data = array();
  drupal_set_header('Content-type: text/plain; charset: utf-8');
  if (!$prefetch) {
		global $simple_data;
		echo json_encode($simple_data);
		exit();
	}
	//Pre fetch data from db
	$result = db_query("SELECT tid, name FROM {term_data} WHERE LOWER(name) LIKE '%%%s%' AND vid = %d", strtolower($_GET['term']), (int)$_GET['vid']);
  while($obj = db_fetch_object($result)) {
    $json = array();
    $json['value'] = $obj->name;
    $json['name'] = $obj->name;
    $json['tid'] = $obj->tid;
    $data[] = $json;
  }
  echo json_encode($data);
}

//==========================================//
// DEFINE THE FIELD
//==========================================//

/**
* Implementation of hook_help().
*/
function autocomplete_dropbox_help($path, $arg) {
  if ($path == 'admin/help#autocomplete_dropbox') {
		return 'A module to aid the process of tagging a node with multiple taxonomy terms by suplying an autocomplete and tag method.';
	}
}

/**
* Implementation of hook_field_info().
*/
function autocomplete_dropbox_field_info() {
  return array(
    'autocomplete_dropbox' => array( // The machine name of the field.
      'label' => t('Auto Complete Dropbox'), // Human-readable label of field, seen in Manage fields screen.
      'description' => t('Store multiple items in one field.'), // Description of what type of data the field stores.
    ),
  );
}

/**
* Implementation of hook_field_settings().
*/
function autocomplete_dropbox_field_settings($op, $field) {
  switch ($op) {
    case 'form':
    //Create the settings form for selecting which vocabulary to use for autocompletion
		$vocabularies = array();
		foreach(taxonomy_get_vocabularies() as $vocabulary) {
			$vocabularies[$vocabulary->vid] = $vocabulary->name;
		}
		$form = array();
    $form['vocabulary_id'] = array(
      '#type'   => 'select',
      '#title'  => t('Auto Complete Vocabulary ID'), 
      '#default_value' => $field['vocabulary_id'] ? $field['vocabulary_id'] : '',
      '#required' => TRUE,
			'#options' => $vocabularies,
      '#description' => t('The id of the vocabulary to be used to populate the autocomplete dropbox suggestions.'),
    );
    $form['term_limit'] = array(
      '#type'   => 'textfield',
      '#title'  => t('Amount of terms allowed'), 
      '#default_value' => $field['term_limit'] ? $field['term_limit'] : '',
      '#required' => TRUE,
      '#description' => t('The maximum amount of terms allowed to be selected for this field.'),
    );
    return $form;
    case 'database columns':
    // Define the colums that needs to be created in the database for storing the field data
      $columns['term_ids'] = array(
        'type' => 'varchar',
        'length' => 40,
        'not null' => FALSE,
        'sortable' => TRUE,
        'views' => TRUE,
      );
      return $columns;
    case 'save':
      return array('vocabulary_id', 'term_limit');
    
  }
}

/**
* Implementation of hook_field().
*/
function autocomplete_dropbox_field($op, &$node, $field, &$items, $teaser, $page) {
  switch ($op) {
    //~ case 'validate':
      //~ foreach ($items as $delta => $item) {
        //~ if (!empty($item['company']) && empty($item['position'])) {
          //~ form_set_error($item['position'], 'Position cannot be empty. Please provide a position for each job.');
          //~ }
        //~ }
          
    case 'presave':
      foreach ($items as $delta => $value) {
        _autocomplete_dropbox_process($items[$delta], $delta, $field, $node);
      }
    break;
  }
}

function _autocomplete_dropbox_process(&$item, $delta = 0, $field, $node) {
	$history = explode(',', $item['history']);
	$tids = explode(',', $item['saved_tids']);
	$new_tax_terms = explode(',', $item['new_terms']);
	
	// get names of removed terms
	$removed_terms = array();
	$removed_tids = array_diff($history, $tids);
	foreach($removed_tids as $tid) {
		$term = taxonomy_get_term($tid);
		$removed_terms[] = $term->name;
	}
	
	// get all names as of saved terms
	$exception_list = array();
	foreach($tids as $tid) {
		$term = taxonomy_get_term($tid);
		$exception_list[] = $term->name;
	}
	
  // clean array to get all new terms to create
	$new_tax_terms = array_diff($new_tax_terms, $removed_terms, $exception_list);
	$new_tax_terms= array_filter($new_tax_terms, 'strlen');

  //Now lets add the new taxonomy terms to the correct taxonomy
  foreach($new_tax_terms as $new_tax_term) {
		$terms = taxonomy_get_term_by_name($new_tax_term);
		if (count($terms) > 0) {
			// asort($terms);
			$term = array_shift($terms);
			$tids[] = $term->tid;
		} else {
			$newterm = array('vid' => $field['vocabulary_id'], 'name' => $new_tax_term);
			taxonomy_save_term($newterm);
			// $tids[] = $newterm->tid;
			$terms = taxonomy_get_term_by_name($new_tax_term);
			$term = array_shift($terms);
			$tids[] = $term->tid;
		}
  }
  
  //Get the values for the saved_tids array
  $saved_tids = $tids;
	$saved_tids= array_filter($saved_tids, 'strlen');
  $saved_tids = array_unique($saved_tids);
	foreach($saved_tids as $tid) {
    $term = taxonomy_get_term($tid);
    $node->taxonomy[] = $term;
  }
	
  $item['term_ids'] = implode(',', $saved_tids);
}

/**
* Implementation of hook_content_is_empty().
*/
function autocomplete_dropbox_content_is_empty($item, $field) {
  if (empty($item['term_ids'])) {
    return TRUE;
  }
  return FALSE;
}

//==========================================//
// DEFINING A FORMATTER
//==========================================//

/**
* Implementation of hook_theme().
*/
function autocomplete_dropbox_theme() {
  return array(
    // Themes for the formatters.
    'autocomplete_dropbox_formatter_default' => array(
      'arguments' => array('element' => NULL),
    ),
  );
}

/**
* Implementation of hook_field_formatter_info().
*/
function autocomplete_dropbox_field_formatter_info() {
  return array(
    // The machine name of the formatter.
    'default' => array(
      // The human-readable label shown on the Display fields screen.
      'label' => t('Default'),
      // An array of the field types this formatter can be used on.
      'field types' => array('autocomplete_dropbox'),
      'multiple values' => CONTENT_HANDLE_CORE,
    ),
  );
}

/**
* Theme function for 'default' companyfield formatter.
*/
function theme_autocomplete_dropbox_formatter_default($element) {
  //Used to theme the standard output of the field
  $output = $element['#item']['term_ids'];
  return $output;
}

//==========================================//
// DEFINING A WIDGET
//==========================================//

/**
* Implementation of hook_widget_info().
*/
function autocomplete_dropbox_widget_info() {
  return array(
    // The machine name of the widget.
    'autocomplete_dropbox_widget' => array(
      // The human-readable label of the field that will be seen in the Manage fields screen.
      'label' => t('Auto Complete Dropbox'),
      // An array of the field types this widget can be used with.
      'field types' => array('autocomplete_dropbox'),
      'multiple values' => CONTENT_HANDLE_CORE,
      'callbacks' => array(
      'default value' => CONTENT_CALLBACK_DEFAULT,
      ),
    ),
  );
}

/**
* Implementation of hook_widget().
*/
function autocomplete_dropbox_widget(&$form, &$form_state, $field, $items, $delta = 0) {
		$items = _profilewizard_clean_items($items);
		$vid = $field['vocabulary_id'];
    $element['term_ids'] = array(
      '#type' => 'textfield', 
      '#maxlength' => 200, 
      '#weight' => 0,
      '#prefix' => '<div class="dropbox-widget"><div class="form-item"><label>'.$field['widget']['label'].':</label></div><div class="autocomplete-dropbox">',
      '#suffix' => '</div>',
    );
    
    $element['saved_tids'] = array(
      '#type' => 'hidden',
      '#maxlength' => 41,
      '#default_value' => $items[$delta]['term_ids'].',',
      '#weight' => 1,
      '#prefix' => '<div class="saved-tids">',
      '#suffix' => '</div>',
    );
		
		// add history to see if terms where removed
		$element['history'] = array(
      '#type' => 'value',
      '#default_value' => $items[$delta]['term_ids'],
    );
    
    //Get the default values to be displayed
    $default_terms = '';
		foreach(explode(',', $items[$delta]['term_ids']) as $tid) {
			$term = taxonomy_get_term($tid);
			$default_terms[] = $term->name;
		}
		$default_terms = implode(',', $default_terms).',';
    
    $element['new_terms'] = array(
      '#type' => 'hidden',
      '#maxlength' => 200,
      '#default_value' => $default_terms,
      '#weight' => 2,
      '#prefix' => '<div class="new-terms">',
      '#suffix' => '</div>',
    );
    
    $element['this_vid'] = array(
      '#type' => 'hidden',
      '#maxlength' => 43,
      '#default_value' => $vid,
      '#weight' => 3,
      '#prefix' => '<div class="this-vid">',
      '#suffix' => '</div>',
    );
    
    $element['term_id_limit'] = array(
      '#type' => 'hidden',
      '#maxlength' => 5,
      '#default_value' => $field['term_limit'],
      '#weight' => 4,
      '#prefix' => '<div class="this-term-id-limit">',
      '#suffix' => '</div> </div><!--dropbox-widget-->',
    );
    
  return $element;
}

function _profilewizard_clean_items($items = array()) {
	$terms = array();
	$tids = explode(',', $items[0]['term_ids']);
	foreach($tids as $tid) {
		$term = taxonomy_get_term($tid);
		if (!empty($term->tid))
			$terms[] = $term->tid;
	}
	// remove duplicates
	$terms = array_unique($terms);
	return array(array('term_ids' => implode(',', $terms)));
}